import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const credentials = JSON.parse(readFileSync('.data/test-credentials.json', 'utf8'));

test('anonymous writes, originals and media traversal are denied', async ({ page, request }) => {
  await page.goto('/admin'); await expect(page).toHaveURL(/\/admin\/login/);
  const response = await request.post('/api/uploads?journeyId=00000000-0000-4000-8000-000000000001', { headers: { Origin: 'http://localhost:3101' }, multipart: { photo: { name: 'photo.png', mimeType: 'image/png', buffer: readFileSync('.data/e2e-photo.png') } } });
  expect(response.status()).toBe(401);
  expect((await request.get('/api/media/00000000-0000-4000-8000-000000000001')).status()).toBe(401);
  expect((await request.get('/media/journeys/00000000-0000-4000-8000-000000000001/00000000-0000-4000-8000-000000000002/original.png')).status()).toBe(404);
});

test('create, upload, publish, update, delete and restore remain consistent after refresh', async ({ page, browser }) => {
  test.setTimeout(120000);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/admin/login');
  await page.getByLabel('账号', { exact: true }).fill(credentials.username); await page.getByLabel('密码', { exact: true }).fill(credentials.password);
  await page.getByRole('button', { name: '登录管理页 →' }).click(); await expect(page).toHaveURL(/\/admin$/);
  await page.getByRole('button', { name: '＋ 添加旅程', exact: true }).click();
  await page.getByLabel('目的地名称必填').fill('成都'); await page.getByLabel('英文名称', { exact: true }).fill('CHENGDU'); await page.getByLabel('国家 / 地区', { exact: true }).fill('中国');
  await page.getByLabel('页面地址必填').fill('chengdu-test'); await page.getByLabel('旅程标题必填').fill('街巷里的散步');
  await page.getByLabel('开始日期必填').fill('2026-10-01'); await page.getByLabel('结束日期必填').fill('2026-10-06');
  await page.getByRole('button', { name: '创建旅程草稿' }).click(); await expect(page.getByRole('status')).toHaveText(/草稿已保存/);
  await page.reload(); await expect(page.getByRole('heading', { name: '成都的旅行档案' })).toBeVisible();
  const publicContext = await browser.newContext({ reducedMotion: 'reduce' }); const publicPage = await publicContext.newPage();
  await publicPage.goto('/trips/chengdu-test'); await expect(publicPage.getByText('404', { exact: true })).toBeVisible();
  const denied = await page.context().request.post('/api/uploads?journeyId=00000000-0000-4000-8000-000000000001', { headers: { Origin: 'https://untrusted.example' }, multipart: { photo: { name: 'photo.png', mimeType: 'image/png', buffer: readFileSync('.data/e2e-photo.png') } } });
  expect(denied.status()).toBe(403);
  const journeyId = await page.locator('.admin-publish-row a').getAttribute('href');
  const malicious = await page.context().request.post(`/api/uploads?journeyId=${journeyId!.split('/').at(-1)}`, { headers: { Origin: 'http://localhost:3101' }, multipart: { photo: { name: 'fake.png', mimeType: 'image/png', buffer: Buffer.from('<svg onload="alert(1)"/>') } } });
  expect((await malicious.json()).results[0].ok).toBe(false);
  await page.getByLabel('添加照片', { exact: true }).setInputFiles('.data/e2e-photo.png'); await expect(page.getByRole('status')).toHaveText(/上传处理完成/, { timeout: 30000 });
  await page.reload(); await expect(page.locator('.admin-photo')).toHaveCount(1);
  const image = await page.locator('.admin-photo img').getAttribute('src');
  expect((await publicContext.request.get(image!)).status()).toBe(404);
  await page.getByRole('button', { name: '发布旅程', exact: true }).click(); await expect(page.getByRole('status')).toHaveText(/已发布/);
  await publicPage.goto('/trips/chengdu-test'); await expect(publicPage.getByRole('heading', { name: '成都 · 街巷里的散步' })).toBeVisible();
  expect((await publicContext.request.get(image!)).status()).toBe(200);
  const otherEditor = await page.context().newPage(); await otherEditor.goto('/admin');
  await page.getByLabel('旅程标题必填').fill('更新后的旅程标题'); await page.getByRole('button', { name: '保存旅程', exact: true }).click(); await expect(page.getByRole('status')).toHaveText(/旅程内容已保存/);
  await otherEditor.locator('textarea[name=description]').fill('冲突时保留的草稿'); await otherEditor.getByRole('button', { name: '保存旅程', exact: true }).click(); await expect(otherEditor.locator('.admin-messages [role=alert]')).toHaveText(/已被修改/); await expect(otherEditor.locator('textarea[name=description]')).toHaveValue('冲突时保留的草稿');
  await otherEditor.close();
  await page.getByLabel('旅程标题必填').fill('街巷里的散步'); await page.getByRole('button', { name: '保存旅程', exact: true }).click(); await expect(page.getByRole('status')).toHaveText(/旅程内容已保存/);
  await page.getByLabel('照片标题', { exact: true }).fill('人民公园的清晨'); await page.getByRole('button', { name: '保存相册' }).click(); await expect(page.getByRole('status')).toHaveText(/相册已保存/);
  await publicPage.reload(); await expect(publicPage.getByRole('button', { name: '放大查看：人民公园的清晨', exact: true })).toBeVisible();
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: '删除照片', exact: true }).click(); await expect(page.getByRole('status')).toHaveText(/照片已移入/);
  await page.getByText('照片回收区 · 1', { exact: true }).click(); await page.getByRole('button', { name: '恢复照片', exact: true }).click(); await expect(page.getByRole('status')).toHaveText(/照片已恢复/);
  await page.getByRole('button', { name: '删除整段旅程', exact: true }).click(); await page.getByRole('button', { name: '确认删除旅程' }).click(); await expect(page.getByRole('status')).toHaveText(/整段旅程已移入/);
  await publicPage.reload(); await expect(publicPage.getByText('404', { exact: true })).toBeVisible();
  expect((await publicContext.request.get(image!)).status()).toBe(404);
  await page.reload(); await page.getByRole('button', { name: /回收区 · 1/ }).click(); await page.getByRole('button', { name: '恢复旅程与相册' }).click(); await expect(page.getByRole('status')).toHaveText(/旅程与相册已恢复/);
  await page.reload(); await expect(page.getByLabel('照片标题', { exact: true })).toHaveValue('人民公园的清晨');
  await publicPage.reload(); await expect(publicPage.getByRole('heading', { name: '成都 · 街巷里的散步' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.data/previews/production-admin-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.screenshot({ path: '.data/previews/production-admin.png', fullPage: true });
  await publicPage.screenshot({ path: '.data/previews/production-journal.png', fullPage: true });
  await publicContext.close();
});
